# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70693b63e7994d12b19ef2354b012a2ef9bd8d7596407445e51c7e011d5d6e701099f75ece46b9e9ac4d3502950224e13fa39ef03ebc29b929fced1030ec6ea8

test:
  secret_key_base: 0f2d287e266f5b27ce3e16836749cdfb57fef3c01c0f5bd518da7bbe9d06086dc460c743aa55bdce9d1fdc4bf06a0c7ac3c4eb371517264d0fe83ed4730ab57d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
