Sneaker.create!([
  {name: "Kobe1", brand: "Nike", cost: 99.99, color: "Black", store_id: 1},
  {name: "Kobe2", brand: "Nike", cost: 99.99, color: "Indian Red", store_id: 1},
  {name: "Kobe3", brand: "Nike", cost: 99.99, color: "Blue", store_id: 1},
  {name: "Kobe4", brand: "Nike", cost: 99.99, color: "Green", store_id: 1},
  {name: "Kobe5", brand: "Nike", cost: 99.99, color: "Gray", store_id: 1},
  {name: "Kobe6", brand: "Nike", cost: 99.99, color: "Yellow", store_id: 1},
  {name: "Kobe7", brand: "Nike", cost: 99.99, color: "Indian Red", store_id: 1},
  {name: "Kobe8", brand: "Nike", cost: 99.99, color: "Blue", store_id: 1},
  {name: "Kobe9", brand: "Nike", cost: 99.99, color: "Green", store_id: 1},
  {name: "KobeX", brand: "Nike", cost: 99.99, color: "Black", store_id: 1},
  {name: "Jordan1", brand: "Nike", cost: 119.99, color: "Black", store_id: 1},
  {name: "Jordan2", brand: "Nike", cost: 119.99, color: "Indian Red", store_id: 1},
  {name: "Jordan3", brand: "Nike", cost: 119.99, color: "Blue", store_id: 1},
  {name: "Jordan4", brand: "Nike", cost: 119.99, color: "Green", store_id: 1},
  {name: "Jordan5", brand: "Nike", cost: 119.99, color: "Gray", store_id: 1},
  {name: "Jordan6", brand: "Nike", cost: 119.99, color: "Yellow", store_id: 1},
  {name: "Jordan7", brand: "Nike", cost: 119.99, color: "Indian Red", store_id: 1},
  {name: "Jordan8", brand: "Nike", cost: 119.99, color: "Black", store_id: 1},
  {name: "Jordan9", brand: "Nike", cost: 119.99, color: "Blue", store_id: 1},
  {name: "JordanX", brand: "Nike", cost: 119.99, color: "Green", store_id: 1},
])

Store.create!([
  {name: "Ara Hodkiewicz", address: "5615 Lincoln Mountain", city: "New Rubye", state: "Texas", zipcode: "78206"},
  {name: "Quentin Walter II", address: "53212 Meggie Oval", city: "Joelfort", state: "Florida", zipcode: "40854"},
  {name: "Delphine Bahringer II", address: "6546 Hand Glens", city: "East Mariamland", state: "North Carolina", zipcode: "68929"},
  {name: "Quinton Kunde", address: "9109 Hoppe Green", city: "South Maggie", state: "South Carolina", zipcode: "69976"},
  {name: "Lavinia Koelpin", address: "1989 Reinger Road", city: "West Helena", state: "Alabama", zipcode: "35532"},
  {name: "Elenor Bernier", address: "7822 Armstrong Land", city: "Judsonborough", state: "North Dakota", zipcode: "49576-7274"},
  {name: "Maggie Fay", address: "99546 Itzel Spur", city: "Mathiasfurt", state: "Virginia", zipcode: "15214-8053"},
  {name: "Garnett Hamill Jr.", address: "63948 Halvorson Port", city: "Kleinview", state: "Utah", zipcode: "18989"},
  {name: "Mariana Hudson", address: "4654 Brenda Radial", city: "New Hershelhaven", state: "California", zipcode: "13180"},
  {name: "Everardo Lesch PhD", address: "68947 Katrina Stravenue", city: "Adonisfurt", state: "Illinois", zipcode: "74021"},
  {name: "Alvah Swaniawski", address: "408 Isac Via", city: "Wiltonburgh", state: "Pennsylvania", zipcode: "33696"},
  {name: "Vernie Frami", address: "5382 Tremblay Lodge", city: "Cartwrightberg", state: "Montana", zipcode: "17184-8904"},
  {name: "Owen Gottlieb", address: "46961 Sadie Corner", city: "North Cynthiachester", state: "Ohio", zipcode: "32255-2076"},
  {name: "Cristopher O'Kon", address: "38552 Bailey Island", city: "Alexismouth", state: "South Carolina", zipcode: "81682-1268"},
  {name: "Demarcus Kertzmann", address: "7572 Hartmann Unions", city: "Kurtland", state: "Vermont", zipcode: "87563"},
  {name: "Ms. Ned O'Kon", address: "61136 Norris Fords", city: "Ginostad", state: "Louisiana", zipcode: "69418-3089"},
  {name: "Raleigh Armstrong", address: "1576 Tromp Circles", city: "Port Christelle", state: "Arizona", zipcode: "81909-3193"},
  {name: "Peyton Bruen", address: "499 Gerardo Shoal", city: "Santinochester", state: "Indiana", zipcode: "34486"},
  {name: "Dr. Marielle O'Kon", address: "60884 Cormier Keys", city: "Thompsonberg", state: "Florida", zipcode: "21303-4423"},
  {name: "Sherwood Pouros", address: "2828 Jake Isle", city: "West Lowellview", state: "Kansas", zipcode: "84319"}
])
